language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meancrud' ]; then cd .. && eval "mv $currentfolder generator-meancrud" && cd generator-meancrud; fi

